name: 3rd-test-deploy-gh-pages

on:
  push:
    branches: [ark-endfield-3rd-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build -- -c=production

      - name: Copy index to 404
        run: cp dist/browser/index.html dist/browser/404.html

      - name: Write release info
        uses: actions/github-script@v8
        env:
          COMMIT_SHA: ${{ github.sha }}
        with:
          script: |
            const exitCode = await exec.exec('./scripts/write-release-info.sh',[
              `3rd-test-${process.env.COMMIT_SHA.substring(0, 7)}`,
              'ark-endfield-3rd-test',
              (new Date()).toISOString(),
              'unused-tag',
            ]);

            console.log('Write release info: ' + exitCode);

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: env.DEPLOY == 'true'
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          repository-name: endfield-calc/endfield-calc.github.io
          branch: master
          git-config-name: "github-actions[bot]"
          git-config-email: "41898282+github-actions[bot]@users.noreply.github.com"
          folder: dist/browser
          clean: true
