name: prod
on:
  push:
    branches: [ark-endfield]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build -- -c=production

      - name: Copy index to 404
        run: cp dist/browser/index.html dist/browser/404.html

      - name: Semantic release
        run: npx semantic-release
        env:
          CI_EVENT: ${{ github.event_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: env.DEPLOY == 'true'
        with:
          token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          repository-name: endfield-calc/endfield-calc.github.io
          branch: master
          folder: dist/browser
          clean: true
